USE [VERITYLOCAL]

-- SELECT * FROM PRODUTO
-- SELECT * FROM COSIF
-- SELECT * FROM MOVIMENTO_MANUAL

-- DELETE FROM PRODUTO
-- DELETE FROM COSIF
-- DELETE FROM MOVIMENTO_MANUAL

INSERT INTO PRODUTO VALUES('PRODUTO TESTE - 01',1),('PRODUTO TESTE - 02', 1),('PRODUTO TESTE - 03', 1);

INSERT INTO [COSIF] VALUES('NORM', 1, 1),('OBSOL', 1, 2),('NORM03', 1, 2),('OBSOL4', 1, 1),('OBSOL5', 1, 3),('OBSOL6', 1, 3);

INSERT INTO [dbo].[MOVIMENTO_MANUAL] VALUES(10,2019,1,10.11,'MOVIMENTO2',GETDATE(),'TESTE2',1,51),(10,2019,1,10.50,'MOVIMENTO',GETDATE(),'TESTE',1,50);



CREATE TABLE PRODUTO (
   COD_PRODUTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DES_PRODUTO VARCHAR(30),
   STA_STATUS BIT
);



CREATE TABLE COSIF(
   COD_COSIF INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   COD_CLASSIFICACAO VARCHAR(6) ,
   STA_STATUS BIT,
   COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO)
);


CREATE TABLE MOVIMENTO_MANUAL(
   COD_MOV INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DAT_MES INT NOT NULL,
   DAT_ANO INT NOT NULL,
   NUM_LANCAMENTO INT NOT NULL,   
   VAL_VALOR DECIMAL(18,2) NOT NULL,
   DES_DESCRICAO VARCHAR(50) NOT NULL,
   DAT_MOVIMENTO SMALLDATETIME NOT NULL,
   COD_USUARIO VARCHAR(15) NOT NULL,
   COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO),
   COD_COSIF INT NOT NULL REFERENCES COSIF(COD_COSIF)
);

