USE [VERITYLOCAL]

SELECT * FROM PRODUTO

delete from COSIF

CREATE TABLE PRODUTO (
   COD_PRODUTO INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DES_PRODUTO VARCHAR(30),
   STA_STATUS BIT
);



CREATE TABLE COSIF(
   COD_COSIF INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   COD_CLASSIFICACAO VARCHAR(6) ,
   STA_STATUS BIT,
   COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO)
);


CREATE TABLE MOVIMENTO_MANUAL(
   COD_COSIF INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DAT_MÊS INT NOT NULL,
   DAT_ANO INT NOT NULL,
   NUM_LANCAMENTO INT NOT NULL,   
   VAL_VALOR DECIMAL NOT NULL,
   DES_DESCRICAO VARCHAR(50) NOT NULL,
   DAT_MOVIMENTO SMALLDATETIME NOT NULL,
   COD_USUARIO VARCHAR(15) NOT NULL,
   COD_PRODUTO INT NOT NULL REFERENCES PRODUTO(COD_PRODUTO),
   COD_COSIF INT NOT NULL REFERENCES COSIF(COD_COSIF)
);

